apiVersion: v1
kind: Secret
metadata:
  name: sample-gpg-secret
type: Opaque 
data:
  GPG_PUBLIC_KEY: |
    my multiline base64 encoded public opengpg cert
stringData: 
  GPG_RECIPIENT: admin@example.com
  GPG_TRUST_MODEL: always
  